fixed bug caused by renaming funcs
josharian/semdiffstat pull request #4
Opened 2019-10-12 20:54 UTC by vekemans

Renaming functions is causing to subtract too many changes from "other" changes.
Replicate bug:

file A
```
package main
func main() {
}
func aaaa() {
}
func bbbb() {
}
```
file B
```
package main
//comment
//comment
func main() {
        return
}
func xxxx() {
        return
}
func cccc() {
        return
}
```
output:
```
func aaaa | 2 -- (deleted)
func bbbb | 2 -- (deleted)
func cccc | 3 +++ (inserted)
func main | 1 +
func xxxx | 3 +++ (inserted)
other     | 0
```
bugfix output:
```
func aaaa | 1 - (deleted)
func bbbb | 1 - (deleted)
func cccc | 2 ++ (inserted)
func main | 1 +
func xxxx | 2 ++ (inserted)
other     | 2 ++
```

2019-10-14 11:36 UTC, vekemans commented
I found another bug (and a fix) related to this. The logic needed to sync the "other" diff with the rest of changes is getting complicated. This will happen with all elements that have a body (funcs, structs).
**Maybe we should consider the way we compute the "other" changes altogether.**
Should I open a new pull request for this bugfix?

2019-10-15 20:55 UTC, josharian requested changes
> Maybe we should reconsider the way we compute the "other" changes altogether?

I agree; I don't particularly like how it works now. I'm definitely open to other ideas.

2019-10-15 20:55 UTC, josharian commented on go.go
> +			panic(-1)
```go
panic("negative ins/del counts for other")
```

2019-10-15 20:55 UTC, josharian commented on go.go
> +				ds := x.diffstat(bi, bi)
This doesn't smell right. `bi` is an index into `b`, not `a`. Can you write a comment clarifying why this is correct?

2019-10-15 20:55 UTC, josharian commented on go.go
> +				ln = len(bytes.Split(x.bBytes(bi), newline))
Now that this construction is being used even more, I wonder whether it should be a method on `bySplits`. Something like:

func (x *bySplits) bLineCount(bi int) int {
  return len(bytes.Split(x.bBytes(bi), newline))
}
```

and similar for `aLineCount(ai)`. Or could call it `aLines` or `aNumLines`.

2019-10-16 16:31 UTC, vekemans commented
I'm closing this in favor of #5 . Trying to sync the "other" changes with the rest of changes doesn't seem right, we need another way of calculating "other" that complements the rest of changes.

2019-10-16 16:31 UTC, closed without merging